### PR TITLE
Fix #1 Bug in codebase

### LINKED ISSUE #1: Bug in codebase
https://github.com/ejhayes/passport-otp/blob/70f56fabef54d3f76a9b85171effc9718d67bffa/lib/strategy.js#L57

This isn't really a valid JavaScript line of code

### PR DESCRIPTION
**Pull request by Climax777**
Fixes https://github.com/ejhayes/passport-otp/issues/1

### CODE REVIEW

**Comment by shaunwarman** [comment]
Can we get this in

**Comment by niftylettuce** [comment]
I've published `@ladjs/passport-otp-strategy@1.1.0` in the interim until this is fixed.  Also the code is available as a fork of @Climax777 at https://github.com/ladjs/passport-otp

**Comment by shaunwarman** [comment]
Thanks @niftylettuce - works for me

**Review by ejhayes — APPROVED** [review]

**Comment by niftylettuce** [comment]
please release a new version to npm @ejhayes

**Comment by ejhayes** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/ejhayes/passport-otp/releases/tag/v1.2.0) :rocket:

**Pull request merged**
